### ISSUE TITLE
Users can see their car

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] background color should be green
- [x] create a div that holds car image
- [x] use absolute positioning for the div that holds the car
- [x] display the user's car in the top left corner of the screen
