### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a simple data model that stores which way the user's car is facing
- [x] listen for 'keydown' events on the document
- [x] when user clicks right arrow face the car right
- [x] when user clicks left arrow face the car left
- [x] when user clicks up arrow face the car up
- [x] when user click down arrow face the car down
