### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started
- [x] listen for a push of the space bar and check the value of datamodel.started to see whether to start or stop
- [x] when changing from start to stop move the car using setinterval by a small number of pixels, 3 times or so, to show stopping
- [x] let the car coast a few pixels to give it a smooth stop if possible
