### ISSUE TITLE
User can steer the car

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] listen for keydown events on the arrows
- [ ] when left key is pressed change the orientation/direction of the car to that direction
- [ ] make sure the car is started
- [ ] repeat for each direction
